import { SkincareProduct, Task, GameState } from '../types';

export const INITIAL_GOLD = 500;
export const INITIAL_DIAMOND = 50;
export const INITIAL_LEVEL = 1;

export const SKINCARE_PRODUCTS: SkincareProduct[] = [
  {
    id: 'cleanse_1',
    name: '温和洁面乳',
    type: 'cleanse',
    quality: 'basic',
    effects: { cleanliness: 15, hydration: 5 },
    price: 50,
    description: '温和清洁肌肤，去除污垢',
    icon: '🧴',
    unlockLevel: 1,
  },
  {
    id: 'tone_1',
    name: '保湿化妆水',
    type: 'tone',
    quality: 'basic',
    effects: { hydration: 20, radiance: 5 },
    price: 60,
    description: '补充肌肤水分，平衡 pH 值',
    icon: '💧',
    unlockLevel: 1,
  },
  {
    id: 'serum_1',
    name: '维 C 精华液',
    type: 'serum',
    quality: 'good',
    effects: { radiance: 25, elasticity: 10 },
    price: 120,
    description: '提亮肤色，抗氧化',
    icon: '✨',
    unlockLevel: 2,
  },
  {
    id: 'moisturize_1',
    name: '水润乳液',
    type: 'moisturize',
    quality: 'basic',
    effects: { hydration: 25, elasticity: 5 },
    price: 80,
    description: '锁住水分，保持肌肤滋润',
    icon: '🧴',
    unlockLevel: 1,
  },
  {
    id: 'sunscreen_1',
    name: '清爽防晒霜',
    type: 'sunscreen',
    quality: 'good',
    effects: { health: 20, radiance: 5 },
    price: 100,
    description: '防护紫外线，保护肌肤',
    icon: '☀️',
    unlockLevel: 2,
  },
  {
    id: 'mask_1',
    name: '补水面膜',
    type: 'mask',
    quality: 'excellent',
    effects: { hydration: 40, radiance: 15 },
    price: 150,
    description: '深层补水，紧急修护',
    icon: '🎭',
    unlockLevel: 3,
  },
  {
    id: 'cleanse_2',
    name: '氨基酸洁面',
    type: 'cleanse',
    quality: 'good',
    effects: { cleanliness: 25, hydration: 10 },
    price: 90,
    description: '温和氨基酸配方，深层清洁',
    icon: '🧼',
    unlockLevel: 3,
  },
  {
    id: 'serum_2',
    name: '玻尿酸精华',
    type: 'serum',
    quality: 'excellent',
    effects: { hydration: 35, elasticity: 15 },
    price: 180,
    description: '强效补水，提升弹性',
    icon: '💎',
    unlockLevel: 4,
  },
  {
    id: 'moisturize_2',
    name: '修护面霜',
    type: 'moisturize',
    quality: 'excellent',
    effects: { hydration: 30, elasticity: 20, health: 10 },
    price: 160,
    description: '深层修护，强化肌肤屏障',
    icon: '🧈',
    unlockLevel: 4,
  },
  {
    id: 'tone_2',
    name: '玫瑰纯露',
    type: 'tone',
    quality: 'premium',
    effects: { hydration: 30, radiance: 20, health: 10 },
    price: 200,
    description: '天然玫瑰精华，舒缓保湿',
    icon: '🌹',
    unlockLevel: 5,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_1',
    title: '初次护肤',
    description: '完成一次完整的护肤流程',
    type: 'daily',
    progress: 0,
    target: 1,
    reward: { gold: 50, diamond: 5, experience: 20 },
    status: 'in_progress',
    refreshType: 'daily',
  },
  {
    id: 'task_2',
    title: '补水达人',
    description: '使用化妆水 5 次',
    type: 'daily',
    progress: 0,
    target: 5,
    reward: { gold: 80, diamond: 8, experience: 30 },
    status: 'in_progress',
    refreshType: 'daily',
  },
  {
    id: 'task_3',
    title: '收集控',
    description: '收集 3 种不同的护肤品',
    type: 'collection',
    progress: 0,
    target: 3,
    reward: { gold: 100, diamond: 10, experience: 50 },
    status: 'in_progress',
    refreshType: 'never',
  },
  {
    id: 'task_4',
    title: '肌肤焕新',
    description: '将水分值提升到 50',
    type: 'achievement',
    progress: 0,
    target: 50,
    reward: { gold: 150, diamond: 15, experience: 80 },
    status: 'in_progress',
    refreshType: 'never',
  },
  {
    id: 'task_5',
    title: '日常清洁',
    description: '使用洁面产品 3 次',
    type: 'daily',
    progress: 0,
    target: 3,
    reward: { gold: 60, diamond: 6, experience: 25 },
    status: 'in_progress',
    refreshType: 'daily',
  },
];

export const createInitialGameState = (): GameState => ({
  player: {
    id: 'player_1',
    name: '美容新手',
    level: INITIAL_LEVEL,
    experience: 0,
    gold: INITIAL_GOLD,
    diamond: INITIAL_DIAMOND,
    avatar: '👩',
    createdAt: Date.now(),
    lastLoginAt: Date.now(),
  },
  skinStats: {
    hydration: 30,
    radiance: 30,
    elasticity: 30,
    cleanliness: 50,
    health: 50,
  },
  inventory: {
    products: {},
    unlocked: ['cleanse_1', 'tone_1', 'moisturize_1'],
  },
  tasks: JSON.parse(JSON.stringify(INITIAL_TASKS)),
  shop: {
    items: ['cleanse_1', 'tone_1', 'moisturize_1'],
    limitedItems: [],
  },
  time: {
    hour: 8,
    minute: 0,
    isDaytime: true,
  },
  statistics: {
    totalSkincareSessions: 0,
    totalProductsUsed: 0,
    totalTasksCompleted: 0,
    playTimeMinutes: 0,
  },
  currentRoutine: [],
  routineComplete: false,
});

export const QUALITY_MULTIPLIERS: Record<string, number> = {
  basic: 1,
  good: 1.5,
  excellent: 2,
  premium: 2.5,
};

export const EXP_PER_LEVEL = 100;
